#include <doctest/doctest.h>
#include "probe_vert_generated.h"   // generated by retropark_embed_shader

TEST_CASE("shader embed: probe.vert compiles to valid SPIR-V") {
    REQUIRE(probe_vert_len > 4);
    CHECK(probe_vert[0] == 0x07230203u);   // SPIR-V magic number
}
