file(READ "${SPV}" HEXDATA HEX)
string(LENGTH "${HEXDATA}" HEXLEN)
math(EXPR NWORDS "${HEXLEN} / 8")
set(BODY "static const unsigned int ${SYMBOL}[] = {\n")
set(i 0)
while(i LESS NWORDS)
  math(EXPR OFF "${i} * 8")
  string(SUBSTRING "${HEXDATA}" ${OFF} 8 W)
  # SPIR-V is little-endian words; swap byte order b0b1b2b3 -> b3b2b1b0
  string(SUBSTRING "${W}" 0 2 B0)
  string(SUBSTRING "${W}" 2 2 B1)
  string(SUBSTRING "${W}" 4 2 B2)
  string(SUBSTRING "${W}" 6 2 B3)
  set(BODY "${BODY}0x${B3}${B2}${B1}${B0}u,\n")
  math(EXPR i "${i} + 1")
endwhile()
set(BODY "${BODY}};\nstatic const unsigned long ${SYMBOL}_len = ${NWORDS};\n")
file(WRITE "${HEADER}" "${BODY}")
